version: '3.5'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
        MYSQL_DATABASE: ${DB_NAME}
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql

  adminer:
    depends_on:
        - db
    image: adminer
    restart: always
    ports:
        - 8888:8080
