version: '3.7'

services:
  db:
    container_name: jjfileupload_db
    image: mysql:5.7
    restart: always
    environment:
        MYSQL_DATABASE: ${DB_NAME}
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        LANG: C.UTF-8
    volumes:
      - ./db:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci

  adminer:
    container_name: jjfileupload_adminer
    depends_on:
        - db
    image: adminer
    restart: always
    ports:
        - 8888:8080
